- name: Upload Test Reports
  if: always()
  uses: actions/upload-artifact@v4
  with:
    name: test-reports
    path: target/surefire-reports/

- name: Upload Extent Report
  if: always()
  uses: actions/upload-artifact@v4
  with:
    name: extent-report
    path: test-output/

- name: Upload Screenshots
  if: always()
  uses: actions/upload-artifact@v4
  with:
    name: screenshots
    path: screenshots/